trigger:
  branches:
    include:
      - main

pool:
  name: DevOps_Pool_Jugal

stages:

# ==========================
# Terraform Init
# ==========================
- stage: Init
  displayName: "Terraform Init"

  jobs:
  - job: TerraformInit
    displayName: "Initialize Terraform"

    steps:
    - script: |
        terraform --version
        terraform init
      displayName: "Terraform Init"

# ==========================
# Terraform Plan
# ==========================
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Init

  jobs:
  - job: TerraformPlan
    displayName: "Plan Infrastructure"

    steps:
    - script: |
        terraform init
        terraform plan -out=tfplan
      displayName: "Terraform Plan"


